/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author yoong
 */
public class JFConsultas extends javax.swing.JFrame {

    /**
     * Creates new form JFConsultas
     */
    public JFConsultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBConsulta3 = new javax.swing.JButton();
        jBConsulta1 = new javax.swing.JButton();
        jBConsulta2 = new javax.swing.JButton();
        jBConsulta4 = new javax.swing.JButton();
        jBConsulta8 = new javax.swing.JButton();
        jBConsulta7 = new javax.swing.JButton();
        jBConsulta6 = new javax.swing.JButton();
        jBConsulta5 = new javax.swing.JButton();
        jBConsulta11 = new javax.swing.JButton();
        jBConsulta10 = new javax.swing.JButton();
        jBConsulta9 = new javax.swing.JButton();
        jBConsulta12 = new javax.swing.JButton();
        jBConsulta13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jBConsulta14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Consultas");

        jBConsulta3.setText("Consulta 3");
        jBConsulta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsulta3ActionPerformed(evt);
            }
        });

        jBConsulta1.setText("Consulta 1");
        jBConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsulta1ActionPerformed(evt);
            }
        });

        jBConsulta2.setText("Consulta 2");
        jBConsulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsulta2ActionPerformed(evt);
            }
        });

        jBConsulta4.setText("Consulta 4");
        jBConsulta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsulta4ActionPerformed(evt);
            }
        });

        jBConsulta8.setText("Consulta 8");
        jBConsulta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsulta8ActionPerformed(evt);
            }
        });

        jBConsulta7.setText("Consulta 7");
        jBConsulta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsulta7ActionPerformed(evt);
            }
        });

        jBConsulta6.setText("Consulta 6");
        jBConsulta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsulta6ActionPerformed(evt);
            }
        });

        jBConsulta5.setText("Consulta 5");
        jBConsulta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsulta5ActionPerformed(evt);
            }
        });

        jBConsulta11.setText("Consulta 11");
        jBConsulta11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsulta11ActionPerformed(evt);
            }
        });

        jBConsulta10.setText("Consulta 10");
        jBConsulta10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsulta10ActionPerformed(evt);
            }
        });

        jBConsulta9.setText("Consulta 9");
        jBConsulta9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsulta9ActionPerformed(evt);
            }
        });

        jBConsulta12.setText("Consulta 12");
        jBConsulta12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsulta12ActionPerformed(evt);
            }
        });

        jBConsulta13.setText("Consulta 13");
        jBConsulta13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsulta13ActionPerformed(evt);
            }
        });

        jButton15.setText("Consulta 15");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jBConsulta14.setText("Consulta 14");
        jBConsulta14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsulta14ActionPerformed(evt);
            }
        });

        jButton16.setText("SALIR");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBConsulta2)
                            .addComponent(jBConsulta3)
                            .addComponent(jBConsulta1)
                            .addComponent(jBConsulta4))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBConsulta6)
                            .addComponent(jBConsulta7)
                            .addComponent(jBConsulta5)
                            .addComponent(jBConsulta8))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBConsulta10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBConsulta11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBConsulta12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBConsulta9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBConsulta14)
                            .addComponent(jButton15)
                            .addComponent(jBConsulta13))))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton16)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBConsulta1)
                        .addGap(18, 18, 18)
                        .addComponent(jBConsulta2)
                        .addGap(26, 26, 26)
                        .addComponent(jBConsulta3)
                        .addGap(18, 18, 18)
                        .addComponent(jBConsulta4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBConsulta5)
                        .addGap(18, 18, 18)
                        .addComponent(jBConsulta6)
                        .addGap(26, 26, 26)
                        .addComponent(jBConsulta7)
                        .addGap(18, 18, 18)
                        .addComponent(jBConsulta8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBConsulta9)
                        .addGap(18, 18, 18)
                        .addComponent(jBConsulta10)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBConsulta11)
                            .addComponent(jButton15))
                        .addGap(18, 18, 18)
                        .addComponent(jBConsulta12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBConsulta13)
                        .addGap(18, 18, 18)
                        .addComponent(jBConsulta14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton16)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBConsulta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsulta3ActionPerformed
        // TODO add your handling code here:
        JFConsulta3 cliente = new JFConsulta3();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jBConsulta3ActionPerformed

    private void jBConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsulta1ActionPerformed
        // TODO add your handling code here:
        JFConsulta cliente = new JFConsulta();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jBConsulta1ActionPerformed

    private void jBConsulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsulta2ActionPerformed
        // TODO add your handling code here:
        JFConsulta2 cliente = new JFConsulta2();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jBConsulta2ActionPerformed

    private void jBConsulta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsulta4ActionPerformed
        // TODO add your handling code here:
        JFConsulta4 cliente = new JFConsulta4();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jBConsulta4ActionPerformed

    private void jBConsulta8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsulta8ActionPerformed
        // TODO add your handling code here:
        JFConsulta8 cliente = new JFConsulta8();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jBConsulta8ActionPerformed

    private void jBConsulta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsulta7ActionPerformed
        // TODO add your handling code here:
        JFConsulta7 cliente = new JFConsulta7();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jBConsulta7ActionPerformed

    private void jBConsulta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsulta6ActionPerformed
        // TODO add your handling code here:
        JFConsulta6 cliente = new JFConsulta6();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jBConsulta6ActionPerformed

    private void jBConsulta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsulta5ActionPerformed
        // TODO add your handling code here:
        JFConsulta5 cliente = new JFConsulta5();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jBConsulta5ActionPerformed

    private void jBConsulta11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsulta11ActionPerformed
        // TODO add your handling code here:
        JFConsulta11 cliente = new JFConsulta11();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jBConsulta11ActionPerformed

    private void jBConsulta10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsulta10ActionPerformed
        // TODO add your handling code here:
        JFConsulta10 cliente = new JFConsulta10();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jBConsulta10ActionPerformed

    private void jBConsulta9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsulta9ActionPerformed
        // TODO add your handling code here:
        JFConsulta9 cliente = new JFConsulta9();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jBConsulta9ActionPerformed

    private void jBConsulta12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsulta12ActionPerformed
        // TODO add your handling code here:
        JFConsulta12 cliente = new JFConsulta12();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jBConsulta12ActionPerformed

    private void jBConsulta13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsulta13ActionPerformed
        // TODO add your handling code here:
        JFConsulta13 cliente = new JFConsulta13();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jBConsulta13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        JFConsulta15 cliente = new JFConsulta15();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jBConsulta14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsulta14ActionPerformed
        // TODO add your handling code here:
        JFConsulta14 cliente = new JFConsulta14();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jBConsulta14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        JFVistaPrincipal cliente = new JFVistaPrincipal();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFConsultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsulta1;
    private javax.swing.JButton jBConsulta10;
    private javax.swing.JButton jBConsulta11;
    private javax.swing.JButton jBConsulta12;
    private javax.swing.JButton jBConsulta13;
    private javax.swing.JButton jBConsulta14;
    private javax.swing.JButton jBConsulta2;
    private javax.swing.JButton jBConsulta3;
    private javax.swing.JButton jBConsulta4;
    private javax.swing.JButton jBConsulta5;
    private javax.swing.JButton jBConsulta6;
    private javax.swing.JButton jBConsulta7;
    private javax.swing.JButton jBConsulta8;
    private javax.swing.JButton jBConsulta9;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
